export default [
  {
    title: 'Convert to',
    name: 'toCurr',
    type: 'menulist',
    value: '',
    options: [
      { value: '', label: 'Please select a currency' },
      { value: 'AFA', label: 'Afghan Afghani (1927–2002)' },
      { value: 'ALL', label: 'Albanian Lek' },
      { value: 'DZD', label: 'Algerian Dinar' },
      { value: 'AOA', label: 'Angolan Kwanza' },
      { value: 'ARS', label: 'Argentine Peso' },
      { value: 'AMD', label: 'Armenian Dram' },
      { value: 'AWG', label: 'Aruban Florin' },
      { value: 'AUD', label: 'Australian Dollar' },
      { value: 'AZN', label: 'Azerbaijani Manat' },
      { value: 'BSD', label: 'Bahamian Dollar' },
      { value: 'BHD', label: 'Bahraini Dinar' },
      { value: 'BDT', label: 'Bangladeshi Taka' },
      { value: 'BBD', label: 'Barbadian Dollar' },
      { value: 'BYR', label: 'Belarusian Ruble (2000–2016)' },
      { value: 'BEF', label: 'Belgian Franc' },
      { value: 'BZD', label: 'Belize Dollar' },
      { value: 'BMD', label: 'Bermudan Dollar' },
      { value: 'BTN', label: 'Bhutanese Ngultrum' },
      { value: 'BTC', label: 'Bitcoin' },
      { value: 'BOB', label: 'Bolivian Boliviano' },
      { value: 'BAM', label: 'Bosnia-Herzegovina Convertible Mark' },
      { value: 'BWP', label: 'Botswanan Pula' },
      { value: 'BRL', label: 'Brazilian Real' },
      { value: 'GBP', label: 'British Pound' },
      { value: 'BND', label: 'Brunei Dollar' },
      { value: 'BGN', label: 'Bulgarian Lev' },
      { value: 'BIF', label: 'Burundian Franc' },
      { value: 'KHR', label: 'Cambodian Riel' },
      { value: 'CAD', label: 'Canadian Dollar' },
      { value: 'CVE', label: 'Cape Verdean Escudo' },
      { value: 'KYD', label: 'Cayman Islands Dollar' },
      { value: 'XAF', label: 'Central African CFA Franc' },
      { value: 'XPF', label: 'CFP Franc' },
      { value: 'CLP', label: 'Chilean Peso' },
      { value: 'CNY', label: 'Chinese Yuan' },
      { value: 'COP', label: 'Colombian Peso' },
      { value: 'KMF', label: 'Comorian Franc' },
      { value: 'CDF', label: 'Congolese Franc' },
      { value: 'CRC', label: 'Costa Rican Colón' },
      { value: 'HRK', label: 'Croatian Kuna' },
      { value: 'CUC', label: 'Cuban Convertible Peso' },
      { value: 'CZK', label: 'Czech Koruna' },
      { value: 'DKK', label: 'Danish Krone' },
      { value: 'DJF', label: 'Djiboutian Franc' },
      { value: 'DOP', label: 'Dominican Peso' },
      { value: 'XCD', label: 'East Caribbean Dollar' },
      { value: 'EGP', label: 'Egyptian Pound' },
      { value: 'ERN', label: 'Eritrean Nakfa' },
      { value: 'EEK', label: 'Estonian Kroon' },
      { value: 'ETB', label: 'Ethiopian Birr' },
      { value: 'EUR', label: 'Euro' },
      { value: 'FKP', label: 'Falkland Islands Pound' },
      { value: 'FJD', label: 'Fijian Dollar' },
      { value: 'GMD', label: 'Gambian Dalasi' },
      { value: 'GEL', label: 'Georgian Lari' },
      { value: 'DEM', label: 'German Mark' },
      { value: 'GHS', label: 'Ghanaian Cedi' },
      { value: 'GIP', label: 'Gibraltar Pound' },
      { value: 'GRD', label: 'Greek Drachma' },
      { value: 'GTQ', label: 'Guatemalan Quetzal' },
      { value: 'GNF', label: 'Guinean Franc' },
      { value: 'GYD', label: 'Guyanaese Dollar' },
      { value: 'HTG', label: 'Haitian Gourde' },
      { value: 'HNL', label: 'Honduran Lempira' },
      { value: 'HKD', label: 'Hong Kong Dollar' },
      { value: 'HUF', label: 'Hungarian Forint' },
      { value: 'ISK', label: 'Icelandic Króna' },
      { value: 'INR', label: 'Indian Rupee' },
      { value: 'IDR', label: 'Indonesian Rupiah' },
      { value: 'IRR', label: 'Iranian Rial' },
      { value: 'IQD', label: 'Iraqi Dinar' },
      { value: 'ILS', label: 'Israeli New Shekel' },
      { value: 'ITL', label: 'Italian Lira' },
      { value: 'JMD', label: 'Jamaican Dollar' },
      { value: 'JPY', label: 'Japanese Yen' },
      { value: 'JOD', label: 'Jordanian Dinar' },
      { value: 'KZT', label: 'Kazakhstani Tenge' },
      { value: 'KES', label: 'Kenyan Shilling' },
      { value: 'KWD', label: 'Kuwaiti Dinar' },
      { value: 'KGS', label: 'Kyrgystani Som' },
      { value: 'LAK', label: 'Laotian Kip' },
      { value: 'LVL', label: 'Latvian Lats' },
      { value: 'LBP', label: 'Lebanese Pound' },
      { value: 'LSL', label: 'Lesotho Loti' },
      { value: 'LRD', label: 'Liberian Dollar' },
      { value: 'LYD', label: 'Libyan Dinar' },
      { value: 'LTL', label: 'Lithuanian Litas' },
      { value: 'MOP', label: 'Macanese Pataca' },
      { value: 'MKD', label: 'Macedonian Denar' },
      { value: 'MGA', label: 'Malagasy Ariary' },
      { value: 'MWK', label: 'Malawian Kwacha' },
      { value: 'MYR', label: 'Malaysian Ringgit' },
      { value: 'MVR', label: 'Maldivian Rufiyaa' },
      { value: 'MRO', label: 'Mauritanian Ouguiya' },
      { value: 'MUR', label: 'Mauritian Rupee' },
      { value: 'MXN', label: 'Mexican Peso' },
      { value: 'MDL', label: 'Moldovan Leu' },
      { value: 'MNT', label: 'Mongolian Tugrik' },
      { value: 'MAD', label: 'Moroccan Dirham' },
      { value: 'MZM', label: 'Mozambican Metical (1980–2006)' },
      { value: 'MMK', label: 'Myanmar Kyat' },
      { value: 'NAD', label: 'Namibian Dollar' },
      { value: 'NPR', label: 'Nepalese Rupee' },
      { value: 'ANG', label: 'Netherlands Antillean Guilder' },
      { value: 'TWD', label: 'New Taiwan Dollar' },
      { value: 'NZD', label: 'New Zealand Dollar' },
      { value: 'NIO', label: 'Nicaraguan Córdoba' },
      { value: 'NGN', label: 'Nigerian Naira' },
      { value: 'KPW', label: 'North Korean Won' },
      { value: 'NOK', label: 'Norwegian Krone' },
      { value: 'OMR', label: 'Omani Rial' },
      { value: 'PKR', label: 'Pakistani Rupee' },
      { value: 'PAB', label: 'Panamanian Balboa' },
      { value: 'PGK', label: 'Papua New Guinean Kina' },
      { value: 'PYG', label: 'Paraguayan Guarani' },
      { value: 'PEN', label: 'Peruvian Sol' },
      { value: 'PHP', label: 'Philippine Peso' },
      { value: 'PLN', label: 'Polish Zloty' },
      { value: 'QAR', label: 'Qatari Rial' },
      { value: 'RON', label: 'Romanian Leu' },
      { value: 'RUB', label: 'Russian Ruble' },
      { value: 'RWF', label: 'Rwandan Franc' },
      { value: 'SVC', label: 'Salvadoran Colón' },
      { value: 'WST', label: 'Samoan Tala' },
      { value: 'SAR', label: 'Saudi Riyal' },
      { value: 'RSD', label: 'Serbian Dinar' },
      { value: 'SCR', label: 'Seychellois Rupee' },
      { value: 'SLL', label: 'Sierra Leonean Leone' },
      { value: 'SGD', label: 'Singapore Dollar' },
      { value: 'SKK', label: 'Slovak Koruna' },
      { value: 'SBD', label: 'Solomon Islands Dollar' },
      { value: 'SOS', label: 'Somali Shilling' },
      { value: 'ZAR', label: 'South African Rand' },
      { value: 'KRW', label: 'South Korean Won' },
      { value: 'XDR', label: 'Special Drawing Rights' },
      { value: 'LKR', label: 'Sri Lankan Rupee' },
      { value: 'SHP', label: 'St. Helena Pound' },
      { value: 'SDG', label: 'Sudanese Pound' },
      { value: 'SRD', label: 'Surinamese Dollar' },
      { value: 'SZL', label: 'Swazi Lilangeni' },
      { value: 'SEK', label: 'Swedish Krona' },
      { value: 'CHF', label: 'Swiss Franc' },
      { value: 'SYP', label: 'Syrian Pound' },
      { value: 'STD', label: 'São Tomé &amp; Príncipe Dobra' },
      { value: 'TJS', label: 'Tajikistani Somoni' },
      { value: 'TZS', label: 'Tanzanian Shilling' },
      { value: 'THB', label: 'Thai Baht' },
      { value: 'TOP', label: 'Tongan Paʻanga' },
      { value: 'TTD', label: 'Trinidad &amp; Tobago Dollar' },
      { value: 'TND', label: 'Tunisian Dinar' },
      { value: 'TRY', label: 'Turkish Lira' },
      { value: 'TMT', label: 'Turkmenistani Manat' },
      { value: 'UGX', label: 'Ugandan Shilling' },
      { value: 'UAH', label: 'Ukrainian Hryvnia' },
      { value: 'AED', label: 'United Arab Emirates Dirham' },
      { value: 'UYU', label: 'Uruguayan Peso' },
      { value: 'USD', label: 'US Dollar' },
      { value: 'UZS', label: 'Uzbekistani Som' },
      { value: 'VUV', label: 'Vanuatu Vatu' },
      { value: 'VEF', label: 'Venezuelan Bolívar' },
      { value: 'VND', label: 'Vietnamese Dong' },
      { value: 'XOF', label: 'West African CFA Franc' },
      { value: 'YER', label: 'Yemeni Rial' },
      { value: 'ZMK', label: 'Zambian Kwacha (1968–2012)' },
    ],
  },
  {
    title: 'Round price',
    name: 'round',
    type: 'bool',
    value: true,
  },
  {
    title: 'Currency symbol',
    name: 'symbol',
    type: 'string',
    value: '',
  },
  {
    title: 'Symbol position',
    name: 'symbPos',
    type: 'radio',
    value: 'a',
    options: [
      {
        value: 'b',
        label: 'before',
      },
      {
        value: 'a',
        label: 'after',
      },
    ],
  },
  {
    title: 'Separate symbol from price',
    name: 'symbSep',
    type: 'bool',
    value: true,
  },
  {
    title: 'Thousand separator',
    name: 'sepTho',
    type: 'menulist',
    value: ' ',
    options: [
      {
        value: '',
        label: 'none',
      },
      {
        value: ' ',
        label: 'space',
      },
      {
        value: ',',
        label: ',',
      },
      {
        value: '.',
        label: '.',
      },
    ],
  },
  {
    title: 'Decimal separator',
    name: 'sepDec',
    type: 'menulist',
    value: ',',
    options: [
      {
        value: ',',
        label: ',',
      },
      {
        value: '.',
        label: '.',
      },
    ],
  },
  {
    title: 'Add custom style to converted prices',
    name: 'style',
    type: 'bool',
    value: true,
  },
  {
    title: 'Show exchange rate update notifications',
    name: 'noti',
    type: 'bool',
    value: true,
  },
];
